/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms. */

const max = 4000000;
let n = 1;
let n1 = 1;
let n2 = 0;
let accum = 0;

while (n2 < max) {
  n2 = n + n1;
  if (n2 < max && n2 % 2 == 0) {
    accum += n2;
  }
  n = n1;
  n1 = n2;
}
console.log(accum);
