/* The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors? */

let actualNaturalNumber = 0;
let actualTrinagleNumber = 0;
const MAX_QUANTITY_DIVISORS = 500;
function nextNatural() {
  actualNaturalNumber += 1;
  return actualNaturalNumber;
}
function nextTriangleNumber() {
  actualTrinagleNumber += nextNatural();
  return actualTrinagleNumber;
}
function numberOfDivisors(number) {
  let divisorsQuantity = 0;
  for (let index = 1; index <= number; index++) {
    if (number % index == 0) {
      divisorsQuantity++;
    }
  }
  return divisorsQuantity;
}

function quantityOfTriangleDivisors() {
  let quantityOfDivisors = 0;
  while (quantityOfDivisors < MAX_QUANTITY_DIVISORS) {
    nextTriangleNumber();
    quantityOfDivisors = numberOfDivisors(actualTrinagleNumber);
    console.log(
      `N:${actualNaturalNumber} - T:${actualTrinagleNumber} - D:${quantityOfDivisors}`
    );
  }
  return actualTrinagleNumber;
}
console.log(quantityOfTriangleDivisors());
